services:
  mysql:
    image: mysql:8.0
    container_name: s8360-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hw4pass
      MYSQL_DATABASE: s8360_rel
    ports:
      - "3306:3306"
    volumes:
      - s8360_mysql_data:/var/lib/mysql

volumes:
  s8360_mysql_data:
